### ISSUE TITLE
Cannot Find some QR Codes

### ISSUE THREAD

**Issue by herman1vdb** [EddyVerbruggen/barcodescanner-lib-aar#15]
Problematic QR Code:
![image](https://user-images.githubusercontent.com/8955362/32093202-cb1d737c-bafb-11e7-899e-98686c6d4b55.png)

Finding (also changing the angle of the QR code to 45° scans successfully):
![image](https://user-images.githubusercontent.com/8955362/32093249-f5e1f402-bafb-11e7-84c1-daaf8513821a.png)

**Comment by herman1vdb** [comment]
After further investigation it seems the vertical and horizontal pattern is accepted at the incorrect center, for this particular QR Code.
Which lead me to come across these concerns:

It seems at [FinderPatternFinder.java:78](https://github.com/EddyVerbruggen/barcodescanner-lib-aar/blob/361a0733ac60d17f89c15695fb29ca011f87134d/barcodescanner/src/main/java/com/google/zxing/qrcode/detector/FinderPatternFinder.java#L78)
`pureBarcode = hints != null && hints.containsKey(DecodeHintType.PURE_BARCODE);`
the default for `pureBarcode` is false (I'd rather assume most QR Codes are pure monochrome?)
eg. `pureBarcode = hints == null || hints.containsKey(DecodeHintType.PURE_BARCODE);`

In any case at [FinderPatternFinder.java:496](https://github.com/EddyVerbruggen/barcodescanner-lib-aar/blob/361a0733ac60d17f89c15695fb29ca011f87134d/barcodescanner/src/main/java/com/google/zxing/qrcode/detector/FinderPatternFinder.java#L496) it seems that the diagonal check is ignored when it is not monochrome (`!pureBarcode || crossCheckDiagonal(...`). This seems strange can someone please explain the reasoning behind this, I don't understand it. According to me it should still do the check regardless if it is a `pureBarcode` or not.

_Unfortunately I'm currently unable to run any tests_

**meaning of Pure Barcode:**
```
  /**
   * Image is a pure monochrome image of a barcode. Doesn't matter what it maps to;
   * use {@link Boolean#TRUE}.
   */
  PURE_BARCODE(Void.class),
```
_DecodeHintType.java_

**Comment by EddyVerbruggen** [comment]
Hi, I think you're best off asking this at the repo where this is actually maintained. The code you found in this repo is similar to the original: https://github.com/zxing/zxing/blob/master/core/src/main/java/com/google/zxing/qrcode/detector/FinderPatternFinder.java

Sorry that it's not too clear that this is 'soft fork'.

**Comment by herman1vdb** [comment]
Ok will do.
Further down the Rabbit hole I go :)

**Comment by EddyVerbruggen** [comment]
Haha, good luck! 👍

**Comment by herman1vdb** [comment]
@EddyVerbruggen can you please update with the fix https://github.com/zxing/zxing/pull/906
Can you also updated the phonegap plugin again?
